require("../app/components/auto-image/auto-image.story")
require("../app/components/button/button.story")
require("../app/components/header/header.story")
require("../app/components/icon/icon.story")
require("../app/components/text/text.story")
